const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://bubblescraper.app").replace(/\/$/, "");

export const SITE_URL = siteUrl;
export const SITE_NAME = "Bubble Scraper";

export const toolCategories = [
  {
    name: "Lead generation",
    summary: "Find public business contacts, company listings, emails, phone numbers, and local leads.",
  },
  {
    name: "Search and website data",
    summary: "Collect search result URLs, scrape live pages, extract documents, images, and structured website data.",
  },
  {
    name: "Verification and enrichment",
    summary: "Validate emails, phone numbers, WhatsApp numbers, domains, and source freshness before export.",
  },
  {
    name: "Social and ad intelligence",
    summary: "Analyze public social profiles, social URLs, and Facebook Ad Library signals from verifiable sources.",
  },
  {
    name: "Jobs and corporate research",
    summary: "Search direct career pages, corporate websites, B2C datasets, and business inquiry workflows.",
  },
];

export const seoTools = [
  {
    name: "Business Directory Scraper",
    path: "/dashboard/business-directory-scraper",
    category: "Lead generation",
    description: "Scrape business directory listings and organize lead data for outreach workflows.",
    answers: ["business directory scraper", "local lead scraper", "directory data extraction"],
  },
  {
    name: "Justdial Scraper",
    path: "/dashboard/justdial-scraper",
    category: "Lead generation",
    description: "Collect public Justdial business listing details for local lead research.",
    answers: ["justdial scraper", "justdial lead scraper", "scrape justdial listings"],
  },
  {
    name: "IndiaMART Scraper",
    path: "/dashboard/indiamart-scraper",
    category: "Lead generation",
    description: "Collect public IndiaMART supplier and business listing data for B2B lead research.",
    answers: ["indiamart scraper", "indiamart supplier scraper", "b2b lead scraper"],
  },
  {
    name: "Sulekha Scraper",
    path: "/dashboard/sulekha-scraper",
    category: "Lead generation",
    description: "Collect public Sulekha service listing details for local service lead workflows.",
    answers: ["sulekha scraper", "sulekha lead scraper", "service listing scraper"],
  },
  {
    name: "Google Maps Scraper",
    path: "/dashboard/google-map-scraper",
    category: "Lead generation",
    description: "Extract public Google Maps business details such as names, categories, locations, websites, and contact fields.",
    answers: ["google maps scraper", "local business leads", "maps lead generation"],
  },
  {
    name: "Email Scraper",
    path: "/dashboard/email-scraper",
    category: "Lead generation",
    description: "Find email addresses from public webpages and export clean prospect lists.",
    answers: ["email scraper", "extract emails from website", "email lead finder"],
  },
  {
    name: "Phone Number Scraper",
    path: "/dashboard/phone-number-scraper",
    category: "Lead generation",
    description: "Extract public phone numbers from websites, pages, and lead sources.",
    answers: ["phone number scraper", "extract phone numbers", "lead phone finder"],
  },
  {
    name: "WhatsApp Number Scraper",
    path: "/dashboard/whatsapp-number-scraper",
    category: "Lead generation",
    description: "Collect public WhatsApp-ready phone numbers for compliant contact list preparation.",
    answers: ["whatsapp number scraper", "whatsapp lead scraper", "find whatsapp numbers"],
  },
  {
    name: "Search Engine Scraper",
    path: "/dashboard/search-engine-scraper",
    category: "Search and website data",
    description: "Collect search result URLs from engines such as Bing, Google, Yahoo, and DuckDuckGo for research workflows.",
    answers: ["bing search scraper", "search engine scraper", "serp scraper"],
  },
  {
    name: "Live Website Scraping",
    path: "/dashboard/live-website-scraping",
    category: "Search and website data",
    description: "Scrape a live webpage and turn public page content into structured data for analysis.",
    answers: ["live website scraper", "web page scraper", "scrape website data"],
  },
  {
    name: "Website Data Scraper",
    path: "/dashboard/website-data-scraper",
    category: "Search and website data",
    description: "Extract titles, descriptions, links, contact details, and structured fields from public websites.",
    answers: ["website data scraper", "extract website data", "web data extraction"],
  },
  {
    name: "Document Scraper",
    path: "/dashboard/document-data-scraper",
    category: "Search and website data",
    description: "Extract useful text and data from public documents for research and enrichment.",
    answers: ["document scraper", "pdf data extraction", "document data scraper"],
  },
  {
    name: "Image Scraper",
    path: "/dashboard/image-data-scraper",
    category: "Search and website data",
    description: "Collect image URLs and image metadata from public webpages.",
    answers: ["image scraper", "extract images from website", "image data scraper"],
  },
  {
    name: "Email Verifier",
    path: "/dashboard/email-verifier",
    category: "Verification and enrichment",
    description: "Verify email deliverability signals before using contact lists.",
    answers: ["email verifier", "verify email addresses", "email validation"],
  },
  {
    name: "WhatsApp Verifier",
    path: "/dashboard/whatsapp-verifier",
    category: "Verification and enrichment",
    description: "Verify WhatsApp number signals before using contact lists in outreach workflows.",
    answers: ["whatsapp verifier", "verify whatsapp numbers", "whatsapp validation"],
  },
  {
    name: "Phone Verifier",
    path: "/dashboard/phone-verifier",
    category: "Verification and enrichment",
    description: "Check phone number format and validation signals for cleaner datasets.",
    answers: ["phone verifier", "phone number validation", "validate phone numbers"],
  },
  {
    name: "WhatsApp Checker",
    path: "/dashboard/whatsapp-checker",
    category: "Verification and enrichment",
    description: "Check whether phone numbers are reachable as WhatsApp contacts.",
    answers: ["whatsapp checker", "whatsapp number check", "verify whatsapp number"],
  },
  {
    name: "Domain Verifier",
    path: "/dashboard/verified-domains",
    category: "Verification and enrichment",
    description: "Verify domains and organize trusted website sources for scraping workflows.",
    answers: ["domain verifier", "verified domains", "domain validation"],
  },
  {
    name: "URL Checker",
    path: "/dashboard/website-urls-checker",
    category: "Verification and enrichment",
    description: "Check website URLs for reachability and status before scraping or outreach.",
    answers: ["url checker", "website checker", "bulk url status checker"],
  },
  {
    name: "WHOIS Lookup",
    path: "/dashboard/whois-domains",
    category: "Verification and enrichment",
    description: "Look up public WHOIS and domain details for source research and website verification.",
    answers: ["whois lookup", "domain whois checker", "domain ownership lookup"],
  },
  {
    name: "Social Media Scraper",
    path: "/dashboard/social-media-scraper",
    category: "Social and ad intelligence",
    description: "Collect public social profile and post signals from supported social sources.",
    answers: ["social media scraper", "social profile scraper", "social data extraction"],
  },
  {
    name: "Social Background Analysis",
    path: "/dashboard/social-background-analysis",
    category: "Social and ad intelligence",
    description: "Summarize public social media URLs with source-backed context and human review reminders.",
    answers: ["social background analysis", "public social profile analysis", "social media risk summary"],
  },
  {
    name: "Facebook Ad Library",
    path: "/dashboard/facebook-ad-library",
    category: "Social and ad intelligence",
    description: "Research public Facebook ad library data for competitor and campaign intelligence.",
    answers: ["facebook ad library scraper", "ad intelligence", "facebook ads research"],
  },
  {
    name: "eCommerce Scraper",
    path: "/dashboard/ecommerce-scraper",
    category: "Search and website data",
    description: "Extract public product and listing data from supported ecommerce pages for research workflows.",
    answers: ["ecommerce scraper", "product data scraper", "online store scraper"],
  },
  {
    name: "Myntra Scraper",
    path: "/dashboard/myntra-scraper",
    category: "Search and website data",
    description: "Collect public Myntra product listing data for catalog and price research.",
    answers: ["myntra scraper", "myntra product scraper", "fashion ecommerce scraper"],
  },
  {
    name: "Snapdeal Scraper",
    path: "/dashboard/snapdeal-scraper",
    category: "Search and website data",
    description: "Collect public Snapdeal product listing data for ecommerce research.",
    answers: ["snapdeal scraper", "snapdeal product scraper", "marketplace scraper"],
  },
  {
    name: "Job Portal Scraper",
    path: "/dashboard/job-portal-scraper",
    category: "Jobs and corporate research",
    description: "Search direct company career pages for fresh job listings, similar roles, and saved alerts.",
    answers: ["direct career page scraper", "job portal scraper", "company career page search"],
  },
  {
    name: "Corporate Scraper",
    path: "/dashboard/corporate-scraper",
    category: "Jobs and corporate research",
    description: "Collect public company information from corporate websites for research and enrichment.",
    answers: ["corporate scraper", "company data scraper", "corporate research tool"],
  },
  {
    name: "B2C Data",
    path: "/dashboard/b2c-data",
    category: "Jobs and corporate research",
    description: "Organize B2C prospect records and business data for outreach workflows.",
    answers: ["b2c data scraper", "consumer lead data", "b2c prospecting"],
  },
  {
    name: "JustDial Enquiry",
    path: "/dashboard/justdial-enquiry",
    category: "Jobs and corporate research",
    description: "Manage JustDial enquiry records for CRM-style follow-up and business workflows.",
    answers: ["justdial enquiry crm", "justdial lead management", "justdial enquiries"],
  },
  {
    name: "IndiaMART Enquiry",
    path: "/dashboard/indiamart-enquiry",
    category: "Jobs and corporate research",
    description: "Manage IndiaMART enquiry records for CRM-style follow-up and B2B workflows.",
    answers: ["indiamart enquiry crm", "indiamart lead management", "indiamart enquiries"],
  },
  {
    name: "Global Directory Scraper",
    path: "/dashboard/global-directory-scraper",
    category: "Lead generation",
    description: "Search global website and directory sources for public business listing data.",
    answers: ["global directory scraper", "international business directory scraper", "global lead scraper"],
  },
  {
    name: "Language Translator",
    path: "/dashboard/language-translator",
    category: "Verification and enrichment",
    description: "Translate text and scraped content to support multilingual research workflows.",
    answers: ["language translator", "translate scraped data", "multilingual data workflow"],
  },
  {
    name: "Bulk WhatsApp Sender",
    path: "/dashboard/whatsapp-bulk-sender",
    category: "Verification and enrichment",
    description: "Send compliant WhatsApp outreach messages from prepared contact lists.",
    answers: ["bulk whatsapp sender", "whatsapp bulk messaging", "whatsapp outreach tool"],
  },
];

export function absoluteUrl(path = "") {
  return `${SITE_URL}${path}`;
}
